### ISSUE TITLE
Missing sqrt

### ISSUE THREAD

**Issue by andreasnoack** [JuliaComputing/BFloat16s.jl#5]
```julia
julia> sqrt(BFloat16(1.0f0))
ERROR: StackOverflowError:
Stacktrace:
 [1] sqrt(::BFloat16) at ./math.jl:518 (repeats 80000 times)
```

**Comment by ViralBShah** [comment]
Do we not have a generic `sqrt` implementation somewhere? Perhaps @pkofod has one?

**Comment by ViralBShah** [comment]
We can also just use @alanedelman 's Babylonian sqrt demo from his AD notebook.

**Comment by pkofod** [comment]
Not too familiar with this number type. From the readme it seems like it’s okay if it calls the Float32 `sqrt` (insofar that doesn’t calculate stuff in Float64) and convert back to BFloat16? If that’s the case then this is just the issue that’s popped up a few times, that the `fun(x::Real)=fun(float(x))` fallbacks can cause infinite recursion when `float(x)=x`.

**Comment by andreasnoack** [comment]
It looks like https://github.com/JuliaComputing/BFloat16s.jl/pull/3 might be useful here. It looks like most of the standard float functions are currently missing.

**Comment by ViralBShah** [comment]
I think doing enough to get a cholesky/svd working would be useful without going crazy over the full list.
